### ISSUE TITLE
Private dependencies

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-webpack#14]
My encounter with this is in a test suite.

The test suite package file had a `jsonld-signatures` dependency and a `did-veres-one` dependency.  The `did-veres-one` dependency had specified a `jsonld-signatures` dev branch `foo`.

NPM installed these deps as expected:
- The version required directly in test suite was in `test/node_modules/jsonld-signatures`
- The version required by did-veres-one was in `test/node_modules/did-veres-one/node-modules/jsonld-signatures

The webpack bundle did not properly account for this and `did-veres-one` was using the `jsonld-signatures` in `test/node_modules/jsonld-signatures`.

In a test suite, this is an annoyance, but I wonder how we're accounting for this phenomenon for live sites.

Are there webpack settings related to getting the expected behavior.  The expected behavior is that webpack does what Node `require` does related to private dependencies.  Which in this case would mean multiple `jsonld-signatures` instances being included in the bundle.

**Comment by dlongley** [comment]
I believe this has been resolved, closing.
