### ISSUE TITLE
Issues with symlinked modules

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-webpack#2]
When attempting to optimize a module when there are symlinked dependencies, an error is returned along these lines: https://gist.github.com/mattcollier/46ed05ea80d7f3da24edce0de8437a35

I have found this babel issue which seems to be relevant: https://github.com/babel/babel-loader/issues/149

We have a need to optimize protractor test suites and I'm encountering the same issue there.  In that case, there is no symlink involved, but I believe babel is getting confused by the paths of the two different pseudo packages.

**Comment by davidlehn** [comment]
I think I may have fixed this.  It requires using `require.resolve('full-package-name')` vs just letting webpack figure out what a shortcut like `name` means.
https://github.com/digitalbazaar/bedrock-webpack/commit/6e1f5bcf207bc2edc599c6b2551a02a484bb9758

**Comment by mandyvenables** [comment]
@davidlehn If this has been fixed, can this issue be closed?

**Comment by davidlehn** [comment]
We no longer use protractor or angular and this code has since been largely rewritten.  Closing as obsolete.
