### ISSUE TITLE
Resolving aliases in `_buildOverrideConfigs` using hard coded path to node modules

### ISSUE THREAD

**Issue by gannan08** [digitalbazaar/bedrock-webpack#8]
@dlongley: "I wonder if this method might be problematic ... and if we should use require.resolve or if the information is already in the package object that bedrock-views generated (I thought maybe we did this somewhere to produce package paths already). If we do generate this path already (or a path to the root package at least), it would be good to reuse that so the code stays in one place.

Leaving this comment here but it shouldn't be a blocker, just worth investigating."

**Comment by dlongley** [comment]
Closing as obsolete.
